module.exports = {
    Games:[
      { gamedate: '14 Junio', gamedateid: 14, gamehourid: 1, group: 'Grupo A', game: 'rusiasaudita', homename: 'Rusia', visitorname: 'A. Saudita', homeflag: 'assets/flags/flag-rusia.png', visitorflag: 'assets/flags/saudita.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '15 Junio', gamedateid: 15, gamehourid: 1, group: 'Grupo A', game: 'egiptouruguay', homename: 'Egipto', visitorname: 'Uruguay', homeflag: 'assets/flags/egipto.png', visitorflag: 'assets/flags/uruguay.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '19 Junio', gamedateid: 19, gamehourid: 2, group: 'Grupo A', game: 'rusiaegipto', homename: 'Rusia', visitorname: 'Egipto', homeflag: 'assets/flags/flag-rusia.png', visitorflag: 'assets/flags/egipto.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '20 Junio', gamedateid: 20, gamehourid: 1, group: 'Grupo A', game: 'uruguaysaudita', homename: 'Uruguay', visitorname: 'A.Saudita', homeflag: 'assets/flags/uruguay.png', visitorflag: 'assets/flags/saudita.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '25 Junio', gamedateid: 25, gamehourid: 1, group: 'Grupo A', game: 'sauditaegipto', homename: 'A.Saudita', visitorname: 'Egipto', homeflag: 'assets/flags/saudita.png', visitorflag: 'assets/flags/egipto.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '25 Junio', gamedateid: 25, gamehourid: 1, group: 'Grupo A', game: 'uruguayrusia', homename: 'Uruguay', visitorname: 'Rusia', homeflag: 'assets/flags/uruguay.png', visitorflag: 'assets/flags/flag-rusia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '15 Junio', gamedateid: 15, gamehourid: 1, group: 'Grupo B', game: 'marruecosiran', homename: 'Marruecos', visitorname: 'Irán', homeflag: 'assets/flags/marrueco.png', visitorflag: 'assets/flags/iran.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '15 Junio', gamedateid: 15, gamehourid: 1, group: 'Grupo B', game: 'portugalespana', homename: 'Portugal', visitorname: 'España', homeflag: 'assets/flags/portugal.png', visitorflag: 'assets/flags/espana.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '20 Junio', gamedateid: 20, gamehourid: 1, group: 'Grupo B', game: 'portuglamarruecos', homename: 'Portugal', visitorname: 'Marruecos', homeflag: 'assets/flags/portugal.png', visitorflag: 'assets/flags/marrueco.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '20 Junio', gamedateid: 20, gamehourid: 1, group: 'Grupo B', game: 'iranespana', homename: 'Irán', visitorname: 'España', homeflag: 'assets/flags/iran.png', visitorflag: 'assets/flags/espana.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '25 Junio', gamedateid: 25, gamehourid: 1, group: 'Grupo B', game: 'espanamarruecos', homename: 'España', visitorname: 'Marruecos', homeflag: 'assets/flags/espana.png', visitorflag: 'assets/flags/marrueco.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '25 Junio', gamedateid: 25, gamehourid: 1, group: 'Grupo B', game: 'iranportugal', homename: 'Irán', visitorname: 'Portugal', homeflag: 'assets/flags/iran.png', visitorflag: 'assets/flags/portugal.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '16 Junio', gamedateid: 16, gamehourid: 1, group: 'Grupo C', game: 'franciaaustralia', homename: 'Francia', visitorname: 'Australia', homeflag: 'assets/flags/francia.png', visitorflag: 'assets/flags/australia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '16 Junio', gamedateid: 16, gamehourid: 1, group: 'Grupo C', game: 'perudinamarca', homename: 'Perú', visitorname: 'Dinamarca', homeflag: 'assets/flags/peru.png', visitorflag: 'assets/flags/dinamarca.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '21 Junio', gamedateid: 21, gamehourid: 1, group: 'Grupo C', game: 'franciaperu', homename: 'Francia', visitorname: 'Perú', homeflag: 'assets/flags/francia.png', visitorflag: 'assets/flags/peru.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '21 Junio', gamedateid: 21, gamehourid: 1, group: 'Grupo C', game: 'dinamarcaaustralia', homename: 'Dinamarca', visitorname: 'Australia', homeflag: 'assets/flags/dinamarca.png', visitorflag: 'assets/flags/australia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '26 Junio', gamedateid: 26, gamehourid: 1, group: 'Grupo C', game: 'australiaperu', homename: 'Australia', visitorname: 'Perú', homeflag: 'assets/flags/australia.png', visitorflag: 'assets/flags/peru.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '26 Junio', gamedateid: 26, gamehourid: 1, group: 'Grupo C', game: 'dinamarcafrancia', homename: 'Dinamarca', visitorname: 'Francia', homeflag: 'assets/flags/dinamarca.png', visitorflag: 'assets/flags/francia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '16 Junio', gamedateid: 16, gamehourid: 1, group: 'Grupo D', game: 'argentinaislandia', homename: 'Argentina', visitorname: 'Islandia', homeflag: 'assets/flags/argentina.png', visitorflag: 'assets/flags/islandia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '16 Junio', gamedateid: 16, gamehourid: 1, group: 'Grupo D', game: 'croacianigeria', homename: 'Croacia', visitorname: 'Nigeria', homeflag: 'assets/flags/croacia.png', visitorflag: 'assets/flags/nigeria.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '21 Junio', gamedateid: 21, gamehourid: 1, group: 'Grupo D', game: 'argentinacroacia', homename: 'Argentina', visitorname: 'Croacia', homeflag: 'assets/flags/argentina.png', visitorflag: 'assets/flags/croacia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '22 Junio', gamedateid: 22, gamehourid: 1, group: 'Grupo D', game: 'nigeriaislandia', homename: 'Nigeria', visitorname: 'Islandia', homeflag: 'assets/flags/nigeria.png', visitorflag: 'assets/flags/islandia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '26 Junio', gamedateid: 26, gamehourid: 1, group: 'Grupo D', game: 'islandiacroacia', homename: 'Islandia', visitorname: 'Croacia', homeflag: 'assets/flags/islandia.png', visitorflag: 'assets/flags/croacia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '26 Junio', gamedateid: 26, gamehourid: 1, group: 'Grupo D', game: 'nigeriaargentia', homename: 'Nigeria', visitorname: 'Argentina', homeflag: 'assets/flags/nigeria.png', visitorflag: 'assets/flags/argentina.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '17 Junio', gamedateid: 17, gamehourid: 1, group: 'Grupo E', game: 'ricaserbia', homename: 'Costa Rica', visitorname: 'Serbia', homeflag: 'assets/flags/costa-rica.png', visitorflag: 'assets/flags/serbia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '17 Junio', gamedateid: 17, gamehourid: 1, group: 'Grupo E', game: 'brasilsuiza', homename: 'Brasil', visitorname: 'Suiza', homeflag: 'assets/flags/brazil.png', visitorflag: 'assets/flags/suiza.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '22 Junio', gamedateid: 22, gamehourid: 1, group: 'Grupo E', game: 'brasilrica', homename: 'Brasil', visitorname: 'Costa Rica', homeflag: 'assets/flags/brazil.png', visitorflag: 'assets/flags/costa-rica.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '22 Junio', gamedateid: 22, gamehourid: 1, group: 'Grupo E', game: 'serbiasuiza', homename: 'Serbia', visitorname: 'Suiza', homeflag: 'assets/flags/serbia.png', visitorflag: 'assets/flags/suiza.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '27 Junio', gamedateid: 27, gamehourid: 1, group: 'Grupo E', game: 'suizarica', homename: 'Suiza', visitorname: 'Costa Rica', homeflag: 'assets/flags/suiza.png', visitorflag: 'assets/flags/costa-rica.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '27 Junio', gamedateid: 27, gamehourid: 1, group: 'Grupo E', game: 'serbiabrasil', homename: 'Serbia', visitorname: 'Brasil', homeflag: 'assets/flags/serbia.png', visitorflag: 'assets/flags/brazil.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '17 Junio', gamedateid: 17, gamehourid: 1, group: 'Grupo F', game: 'alemaniamexico', homename: 'Alemania', visitorname: 'México', homeflag: 'assets/flags/alemania.png', visitorflag: 'assets/flags/mexico.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '18 Junio', gamedateid: 18, gamehourid: 1, group: 'Grupo F', game: 'sueciacorea', homename: 'Suecia', visitorname: 'C.del Sur', homeflag: 'assets/flags/suecia.png', visitorflag: 'assets/flags/corea-sur.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '23 Junio', gamedateid: 23, gamehourid: 1, group: 'Grupo F', game: 'alemaniasuecia', homename: 'Alemania', visitorname: 'Suecia', homeflag: 'assets/flags/alemania.png', visitorflag: 'assets/flags/suecia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '23 Junio', gamedateid: 23, gamehourid: 1, group: 'Grupo F', game: 'coreamexico', homename: 'C.del Sur', visitorname: 'México', homeflag: 'assets/flags/corea-sur.png', visitorflag: 'assets/flags/mexico.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '27 Junio', gamedateid: 27, gamehourid: 1, group: 'Grupo F', game: 'mexicosuecia', homename: 'México', visitorname: 'Suecia', homeflag: 'assets/flags/mexico.png', visitorflag: 'assets/flags/suecia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '27 Junio', gamedateid: 27, gamehourid: 1, group: 'Grupo F', game: 'coreaalemania', homename: 'Corea', visitorname: 'Alemania', homeflag: 'assets/flags/corea-sur.png', visitorflag: 'assets/flags/alemania.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '18 Junio', gamedateid: 18, gamehourid: 1, group: 'Grupo G', game: 'belgicapanama', homename: 'Bélgica', visitorname: 'Panamá', homeflag: 'assets/flags/belgica.png', visitorflag: 'assets/flags/panama.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '18 Junio', gamedateid: 18, gamehourid: 1, group: 'Grupo G', game: 'tunezinglaterra', homename: 'Túnez', visitorname: 'Inglaterra', homeflag: 'assets/flags/tunez.png', visitorflag: 'assets/flags/inglaterra.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '23 Junio', gamedateid: 23, gamehourid: 1, group: 'Grupo G', game: 'belgicatunez', homename: 'Bélgica', visitorname: 'Túnez', homeflag: 'assets/flags/belgica.png', visitorflag: 'assets/flags/tunez.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '24 Junio', gamedateid: 24, gamehourid: 1, group: 'Grupo G', game: 'inglaterrapanama', homename: 'Inglaterra', visitorname: 'Panamá', homeflag: 'assets/flags/inglaterra.png', visitorflag: 'assets/flags/panama.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '28 Junio', gamedateid: 28, gamehourid: 1, group: 'Grupo G', game: 'panamatunez', homename: 'Panamá', visitorname: 'Túnez', homeflag: 'assets/flags/panama.png', visitorflag: 'assets/flags/tunez.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '28 Junio', gamedateid: 28, gamehourid: 1, group: 'Grupo G', game: 'inglaterrabelgica', homename: 'Inglaterra', visitorname: 'Bélgica', homeflag: 'assets/flags/inglaterra.png', visitorflag: 'assets/flags/belgica.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '19 Junio', gamedateid: 19, gamehourid: 1, group: 'Grupo H', game: 'poloniasenegal', homename: 'Polonia', visitorname: 'Senegal', homeflag: 'assets/flags/polonia.png', visitorflag: 'assets/flags/senegal.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '19 Junio', gamedateid: 19, gamehourid: 1, group: 'Grupo H', game: 'colombiajapon', homename: 'Colombia', visitorname: 'Japón', homeflag: 'assets/flags/colombia.png', visitorflag: 'assets/flags/japon.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '24 Junio', gamedateid: 24, gamehourid: 1, group: 'Grupo H', game: 'japonsenegal', homename: 'Japón', visitorname: 'Senegal', homeflag: 'assets/flags/japon.png', visitorflag: 'assets/flags/senegal.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '24 Junio', gamedateid: 24, gamehourid: 1, group: 'Grupo H', game: 'poloniacolombia', homename: 'Polonia', visitorname: 'Colombia', homeflag: 'assets/flags/polonia.png', visitorflag: 'assets/flags/colombia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '28 Junio', gamedateid: 28, gamehourid: 1, group: 'Grupo H', game: 'senegalcolombia', homename: 'Senegal', visitorname: 'Colombia', homeflag: 'assets/flags/senegal.png', visitorflag: 'assets/flags/colombia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  },
      { gamedate: '28 Junio', gamedateid: 28, gamehourid: 1, group: 'Grupo H', game: 'japonpolonia', homename: 'Japón', visitorname: 'Polonia', homeflag: 'assets/flags/japon.png', visitorflag: 'assets/flags/polonia.png', homegoal: undefined, visitorgoal: undefined, isEnded: false  }
    ]

    // {
    //   rusiasauditaRusia: 0, rusiasauditaSaudita: 0,
    //   egiptouruguayEgipto: 0, egiptouruguayUruguay: 0,
    //   rusiaegiptoRusia: 0, rusiaegiptoEgipto: 0,
    //   uruguaysauditaUruguay: 0, uruguaysauditaSaudita: 0,
    //   sauditaegiptoSaudita: 0, sauditaegiptoEgipto: 0,
    //   uruguayrusiaUruguay: 0, uruguayrusiaRusia: 0,
    //   marruecosiranMarruecos: 0, marruecosiranIran: 0,
    //   portugalespanaPortugal: 0, portugalespanaEspana: 0,
    //   portugalmarruecosPortugal: 0, portugalmarruecosMarruecos: 0,
    //   iranespanaIran: 0, iranespanaEspana: 0,
    //   espanamarruecosEspana: 0, espanamarruecosMarruecos: 0,
    //   iranportugalIran: 0, iranportugalPortugal: 0,
    //   franciaaustraliaFrancia: 0, franciaaustraliaAustralia: 0,
    //   perudinamarcaPeru: 0, perudinamarcaDinamarca: 0,
    //   franciaperuFrancia: 0, franciaperuPeru: 0,
    //   dinamarcaaustraliaDinamarca: 0, dinamarcaaustraliaAustralia: 0,
    //   australiaperuAustralia: 0, australiaperuPeru: 0,
    //   dinamarcafranciaDinamarca: 0, dinamarcafranciaFrancia: 0,
    //   argentinaislandiaArgentina: 0, argentinaislandiaIslandia: 0,
    //   croacianigeriaCroacia: 0, croacianigeriaNigeria: 0,
    //   argentinacroaciaArgentina: 0, argentinacroaciaCroacia: 0,
    //   nigeriaislandiaNigeria: 0, nigeriaislandiaIslandia: 0,
    //   islandiacroaciaIslandia: 0, islandiacroaciaCroacia: 0,
    //   nigeriaargentiaNigeria: 0, nigeriaargentiaArgentina: 0,
    //   ricaserbiaRica: 0, ricaserbiaSerbia: 0,
    //   brasilsuizaBrasil: 0, brasilsuizaSuiza: 0,
    //   brasilricaBrasil: 0, brasilricaRica: 0,
    //   serbiasuizaSerbia: 0, serbiasuizaSuiza: 0,
    //   suizaricaSuiza: 0, suizaricaRica: 0,
    //   serbiabrasilSerbia: 0, serbiabrasilBrasil: 0,
    //   alemaniamexicoAlemania: 0, alemaniamexicoMexico: 0,
    //   sueciacoreaSuecia: 0, sueciacoreaCorea: 0,
    //   alemaniasueciaAlemania: 0, alemaniasueciaSuecia: 0,
    //   coreamexicoCorea: 0, coreamexicoMexico: 0,
    //   mexicosueciaMexico: 0, mexicosueciaSuecia: 0,
    //   sueciacoreaSuecia: 0, sueciacoreaCorea: 0,
    //   belgicapanamaBelgica: 0, belgicapanamaPanama: 0,
    //   tunezinglaterraTunez: 0, tunezinglaterraInglaterra: 0,
    //   belgicatunezBelgica: 0, belgicatunezTunez: 0,
    //   inglaterrapanamaInglaterra: 0, inglaterrapanamaPanama: 0,
    //   panamatunezPanama: 0, panamatunezTunez: 0,
    //   inglaterrabelgicaInglaterra: 0, inglaterrabelgicaBelgica: 0,
    //   poloniasenegalPolonia: 0, poloniasenegalSenegala: 0,
    //   colombiajaponColombia: 0, colombiajaponJapon: 0,
    //   japonsenegalJapon: 0, japonsenegalSenegal: 0,
    //   poloniacolombiaPolonia: 0, poloniacolombiaColombia: 0,
    //   senegalcolombiaSenegal: 0, senegalcolombiaColombia: 0,
    //   japonpoloniaJapon: 0, japonpoloniaPolonia: 0
    // }
}
